import { Hind_Siliguri } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import baseUrl from "@/services/baseUrl";

const hindSiliguri = Hind_Siliguri({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ["latin", "bengali"],
});

export const dynamic = 'force-dynamic';

export const metadata = {
  title: "Bazar-Dor",
  description: "Generated by create next app",
};

const getCategories = async()=>{
  const res = await fetch(`${baseUrl}/categories`);
  const data = await res.json();
  return data;
}

export default async function RootLayout({ children }) {
  const categories = await getCategories();
  return (
    <html
      lang="en"
      className={`${hindSiliguri.className} h-full antialiased`}
    >
      <body suppressHydrationWarning className="min-h-full flex flex-col max-w-7xl mx-auto">
        <Navbar categories={categories}/>
        <div className="bg-[#f3f8f4]">{children}</div>
        <Footer/>
        </body>
    </html>
  );
}
