import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

const notoSerifBangali = Noto_Serif_Bengali({
  subsets: ["latin", "bengali"],
});

export const metadata = {
  title: "Bazar-Dor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${notoSerifBangali.className} h-full antialiased`}
    >
      <body suppressHydrationWarning className="min-h-full flex flex-col max-w-7xl mx-auto">
        <Navbar/>
        <div>{children}</div>
        <Footer/>
        </body>
    </html>
  );
}
